import type { NextPage } from "next";
import Head from "next/head";
import styled from "styled-components";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const { data } = trpc.useQuery(["example.hello", { text: "from tRPC" }]);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="color-scheme" content="dark light" />
      </Head>
      <div>
        <StyledH1>h1</StyledH1>
      </div>
    </>
  );
};

export default Home;

const StyledH1 = styled.h1`
  color: var(--link);
`;
